---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sierrao-test-redis-deployment
  labels:
    username: sierrao
    env: test
    app: sierrao-test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      username: sierrao
      env: test
      app: sierrao-test-redis
  template:
    metadata:
      labels:
        username: sierrao
        env: test
        app: sierrao-test-redis
    spec:
      containers:
        - name: sierrao-test-redis
          image: redis:5.0.0
          volumeMounts:
          - name: sierrao-test-data
            mountPath: "/data"
      volumes:
      - name: sierrao-test-data
        persistentVolumeClaim:
          claimName: sierrao-test-data
